name: Carbon Gate Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  carbon-gate:
    runs-on: ubuntu-latest
    name: carbon emissions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Carbon Gate
        uses: ./ # Uses the action in this repo
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-endpoint: ${{ secrets.CARBON_GATE_API_ENDPOINT }}
          org-api-key: ${{ secrets.CARBON_GATE_ORG_KEY }}
          crusoe-api-key: ${{ secrets.CRUSOE_API_KEY }}
          override-signing-secret: ${{ secrets.OVERRIDE_SIGNING_SECRET }}
